version: '3'
services:
  nginx:
    image: florianvigier/4dvop-app:nginx
    ports:
      - "8080:8080"
  haproxy:
    image: florianvigier/4dvop-app:haproxy
    ports:
      - "80:80"
    depends_on:
      - nginx
